This notebook is to explore and prepare for visualization the frequency data

In [2]:
import pandas as pd

Import .csv files from the word_frequency_analysis notebook

In [3]:
df_Rhouse = pd.read_csv('top_R_house_phrases.csv')
df_Dhouse = pd.read_csv('top_D_house_phrases.csv')
df_Rsenate = pd.read_csv('top_R_senate_phrases.csv')
df_Dsenate = pd.read_csv('top_D_senate_phrases.csv')

### Merge the House and Senate dataframes for each party ###

In [4]:
#DEMOCRATS

# create an empty list of rows

D_rows = []

In [5]:
# fill the rows 

senate_only_count = 0
house_only_count = 0
duplicate_count = 0

for i in range(0, 150): # run through each row in the house dataframe

    # locate the noun phrase in that row
    phrase = df_Dhouse.iloc[i]['Noun Phrase']

    if phrase in df_Dsenate['Noun Phrase'].values:  # check if the noun phrase in the SENATE list as well as the HOUSE
        print(f'{phrase} is on both the House and Senate lists.') # if so, print that it is in both
        duplicate_count = duplicate_count + 1 # count up the number of duplicate phrases

        # define information for a new row in new merged dataframe
        
        # locate both frequency numbers
        Dhouse_frequency = df_Dhouse.iloc[i]['Frequency'].item() # in the House df row we're in, find Frequency
        Dsenate_frequency = df_Dsenate.loc[df_Dsenate['Noun Phrase'] == phrase, 'Frequency'].item() # in the Senate df row with the same noun phrase, find its frequency in that df

        # and ad the frequencies together
        Dtotal_frequency = Dhouse_frequency + Dsenate_frequency
    
    # if noun phrase on HOUSE list but NOT SENATE list.
    # add the information into a new row
    elif phrase not in df_Dsenate['Noun Phrase'].values:
        print(f'{phrase} is only on House list.')
        house_only_count = house_only_count + 1
    
        # define information for a new row in new merged dataframe
        Dhouse_frequency = df_Dhouse.iloc[i]['Frequency'].item() # in the House df row, find Frequency in the D House list
        Rsenate_frequency = 0
        Dtotal_frequency = Dhouse_frequency

    # now create the row from the above info
    new_row = {
        'noun_phrase': phrase,
        'Dtotal_frequency': Dtotal_frequency,
        'Dhouse_frequency': Dhouse_frequency,
        'Dsenate_frequency': Dsenate_frequency
    }
    
    D_rows.append(new_row)

the interior is on both the House and Senate lists.
the secretary is on both the House and Senate lists.
the department is on both the House and Senate lists.
representatives is only on House list.
america is only on House list.
the bureau is on both the House and Senate lists.
the state is on both the House and Senate lists.
priorities is only on House list.
" legislative hearing is only on House list.
public lands is on both the House and Senate lists.
impacts is only on House list.
california is on both the House and Senate lists.
public health is only on House list.
oversight is only on House list.
the environment is only on House list.
the impacts is only on House list.
reclamation is on both the House and Senate lists.
climate change is only on House list.
communities is on both the House and Senate lists.
solutions is only on House list.
access is only on House list.
the policies is only on House list.
land management is on both the House and Senate lists.
rep. pete stauber is only on House list.
the mineral withdrawal is only on House list.
the superior national forest is only on House list.
indigenous communities is only on House list.
coastal communities is only on House list.
environmental justice is only on House list.
enforcement is only on House list.
all act is only on House list.
(virtual hearing is only on House list.
diversity is only on House list.
lessons is only on House list.
the need is only on House list.
the interior’s spending priorities is only on House list.
health care is only on House list.
consumers is only on House list.
the u.s. territories is only on House list.
the future is only on House list.
the president’s fiscal year 2020 budget proposal is only on House list.
action is only on House list.
management is on both the House and Senate lists.
the surface mining control and reclamation act is only on House list.
the united states is on both the House and Senate lists.
natural resources is only on House list.
indians is only on House list.
jobs is only on House list.
the use is on both the House and Senate lists.
taxpayers is only on House list.
the mining law is only on House list.
agriculture is on both the House and Senate lists.
h.res is only on House list.
“connecting america is only on House list.
“the future is only on House list.
biomedical research is only on House list.
the budget is only on House list.
puerto rico self-determination act is only on House list.
affordability is only on House list.
civil rights is only on House list.
equity is only on House list.
inclusion is only on House list.
scientific integrity is only on House list.
the puerto rico electric power authority is only on House list.
prepa is only on House list.
virtual hearing is only on House list.
covid-19’s impact is only on House list.
pandemics is only on House list.
the production is only on House list.
hydrofluorocarbons is only on House list.
the economy is only on House list.
ocean energy management is only on House list.
the spending priorities is only on House list.
americans is only on House list.
transparency is only on House list.
conservation is only on House list.
the climate is only on House list.
day is only on House list.
renewable energy is on both the House and Senate lists.
health benefits is only on House list.
miners act is only on House list.
“miners pension protection act is only on House list.
the threats is only on House list.
the national oceanic is only on House list.
u.s. fish is only on House list.
wildlife service is only on House list.
rep. grijalva is only on House list.
"oil and gas development is only on House list.
the u.s. bureau is only on House list.
lands is only on House list.
states is only on House list.
the purpose is only on House list.
land and water resources is only on House list.
august is only on House list.
indian tribes is only on House list.
(rep. lamborn is only on House list.
rep. huffman is only on House list.
the conservation is only on House list.
restoration is only on House list.
offshore drilling is only on House list.
innovation is only on House list.
workers is only on House list.
mmiw is only on House list.
safety is only on House list.
all americans is only on House list.
tribal communities is only on House list.
"climate change is only on House list.
peaceful protesters is only on House list.
mental health is only on House list.
opportunities is on both the House and Senate lists.
atmospheric administration legislative hearing is only on House list.
issuance is only on House list.
subpoenas is only on House list.
mismanagement is only on House list.
waste is only on House list.
fraud is only on House list.
abuse is only on House list.
wrongful conduct is only on House list.
relation is only on House list.
functions is only on House list.
the jurisdiction is only on House list.
policy priorities is only on House list.
america's wildlife act is only on House list.
recreation is only on House list.
federal lands is only on House list.
olympic national forest is on both the House and Senate lists.
"the future is only on House list.
u.s. climate targets is only on House list.
the future act is only on House list.
h.res.1247 is only on House list.
the 2023-2028 five-year program is only on House list.
offshore oil and gas leasing is only on House list.
the compliance is only on House list.
the obligations is only on House list.
the mineral leasing act is only on House list.
h.res.1252 is only on House list.
h.res.1253 is only on House list.
(ranking member bruce westerman is only on House list.
the actions is only on House list.
the interior’s departmental ethics office is only on House list.
the bipartisan infrastructure law is on both the House and Senate lists.
- is only on House list.
need is only on House list.
biomedicine is only on House list.
the u.s nuclear legacy is only on House list.
our communications networks is only on House list.
implementation is on both the House and Senate lists.
the reconciliation directive is only on House list.
the concurrent resolution is only on House list.
res.14 is only on House list.

In [6]:
# Also need to add in the noun phrases on the SENATE but not HOUSE lists:
for i in range(0, 150): # run through the rows in the Senate dataframe

    # locate the Noun Phrase in the row were in 
    phrase = df_Dsenate.iloc[i]['Noun Phrase']
    
    # if noun phrase on SENATE list but NOT HOUSE list:
    if phrase not in df_Dhouse['Noun Phrase'].values:
        print(f'{phrase} is only on Senate list.') # print it out
        senate_only_count = senate_only_count + 1 # count up how many phrases are senate only

        # define information for a new row in new merged dataframe
        Dhouse_frequency = 0 
        Dsenate_frequency = df_Dsenate.iloc[i]['Frequency'].item()
        Dtotal_frequency = Dsenate_frequency

        # create a new column in the merged dataframe with the phrase
        new_row = {
        'noun_phrase': phrase,
        'Dtotal_frequency': Dtotal_frequency,
        'Dhouse_frequency': Dhouse_frequency,
        'Dsenate_frequency': Dsenate_frequency
    }   
        D_rows.append(new_row)

energy is only on Senate list.
an assistant secretary is only on Senate list.
the environmental protection agency is only on Senate list.
virginia is only on Senate list.
the boundary is only on Senate list.
a member is only on Senate list.
director is only on Senate list.
oregon is only on Senate list.
an assistant administrator is only on Senate list.
michigan is only on Senate list.
the nuclear regulatory commission is only on Senate list.
new mexico is only on Senate list.
all is only on Senate list.
certain federal land is only on Senate list.
challenges is only on Senate list.
the wild and scenic rivers act is only on Senate list.
massachusetts is only on Senate list.
colorado is only on Senate list.
department is only on Senate list.
land is only on Senate list.
nevada is only on Senate list.
montana is only on Senate list.
maryland is only on Senate list.
both is only on Senate list.
secretary is only on Senate list.
the district is only on Senate list.
columbia is only on Senate list.
arizona is only on Senate list.
certain land is only on Senate list.
the national park system is only on Senate list.
programs is only on Senate list.
the office is only on Senate list.
pennsylvania is only on Senate list.
texas is only on Senate list.
illinois is only on Senate list.
a unit is only on Senate list.
utah is only on Senate list.
office is only on Senate list.
science is only on Senate list.
north carolina is only on Senate list.
the federal energy regulatory commission is only on Senate list.
new york is only on Senate list.
transportation is only on Senate list.
that is only on Senate list.
components is only on Senate list.
the national wild and scenic rivers system is only on Senate list.
economic development is only on Senate list.
the national park service is only on Senate list.
alaska is only on Senate list.
which is only on Senate list.
nuclear energy is only on Senate list.
david m. uhlmann is only on Senate list.
the opportunities is only on Senate list.
sara c. bronin is only on Senate list.
connecticut is only on Senate list.
chairman is only on Senate list.
the advisory council is only on Senate list.
historic preservation is only on Senate list.
laura daniel-davis is only on Senate list.
the infrastructure investment and jobs act is only on Senate list.
federal land is only on Senate list.
a pilot program is only on Senate list.
the administrator is only on Senate list.
a study is only on Senate list.
the alaska native claims settlement act is only on Senate list.
the forest service is only on Senate list.
washington is only on Senate list.
assistant administrator is only on Senate list.
operation is only on Senate list.
north dakota is only on Senate list.
engineers is only on Senate list.
a program is only on Senate list.
projects is only on Senate list.
kentucky is only on Senate list.
tennessee is only on Senate list.
joseph goffman is only on Senate list.
administrator is only on Senate list.
the federal highway administration is only on Senate list.
federal cochairperson is only on Senate list.
each is only on Senate list.
resiliency is only on Senate list.
the omnibus public land management act is only on Senate list.
the national forest system is only on Senate list.
use is only on Senate list.
state and local perspectives is only on Senate list.
certain outer continental shelf revenues is only on Senate list.
those acts is only on Senate list.
the united states fish and wildlife service is only on Senate list.
the designation is only on Senate list.
the john d. dingell is only on Senate list.
jr. conservation is only on Senate list.
recreation act is only on Senate list.
the rio grande del norte national monument is only on Senate list.
carlton waterhouse is only on Senate list.
solid waste is only on Senate list.
the republic is only on Senate list.
the licensing is only on Senate list.
the water resources development act is only on Senate list.
west virginia is only on Senate list.
the united states courthouse is only on Senate list.
florida is only on Senate list.
entry is only on Senate list.
alaska natives is only on Senate list.
deputy secretary is only on Senate list.
david crane is only on Senate list.
new jersey is only on Senate list.
energy efficiency is only on Senate list.
the energy policy act is only on Senate list.
certain activities is only on Senate list.
uranium is only on Senate list.
leases is only on Senate list.
the dolores river national conservation area is only on Senate list.
the dolores river special management area is only on Senate list.
private water rights is only on Senate list.
its environs is only on Senate list.
the completion is only on Senate list.
the continental divide national scenic trail is only on Senate list.
nuclear waste is only on Senate list.
the tennessee valley authority is only on Senate list.
georgia is only on Senate list.
the clean air act is only on Senate list.
development is only on Senate list.
the national wilderness preservation system is only on Senate list.
the smith river national recreation area act is only on Senate list.
certain additions is only on Senate list.
the smith river national recreation area is only on Senate list.
certain wild rivers is only on Senate list.
the santa monica mountains national recreation area is only on Senate list.
the rim is only on Senate list.
the valley corridor is only on Senate list.
the forest and rangeland renewable resources planning act is only on Senate list.

In [7]:
print(senate_only_count)
print(house_only_count)
print(duplicate_count)

131
131
19

Now create the dataframe

In [8]:
df_D = pd.DataFrame(D_rows)

In [9]:
df_D.sort_values(by = 'Dtotal_frequency', ascending=False).head(20)

,noun_phrase,Dtotal_frequency,Dhouse_frequency,Dsenate_frequency
6,the state,77,7,70
1,the secretary,77,13,64
0,the interior,68,13,55
150,energy,47,0,47
2,the department,38,11,27
44,the united states,28,3,25
51,agriculture,24,3,21
151,an assistant secretary,22,0,22
152,the environmental protection agency,21,0,21
153,virginia,21,0,21
11,california,17,5,12
154,the boundary,17,0,17
155,a member,17,0,17
5,the bureau,15,8,7
156,director,15,0,15
158,an assistant administrator,14,0,14
157,oregon,14,0,14
159,michigan,12,0,12
22,land management,12,4,8
161,new mexico,11,0,11

Now for the Republicans

In [10]:
R_rows = []

In [11]:
# fill the rows 

senate_only_count = 0
house_only_count = 0
duplicate_count = 0

for i in range(0, 150): # run through each row in the house dataframe

    # locate the noun phrase in that row
    phrase = df_Rhouse.iloc[i]['Noun Phrase']

    if phrase in df_Rsenate['Noun Phrase'].values:  # check if the noun phrase in the SENATE list as well as the HOUSE
        print(f'{phrase} is on both the House and Senate lists.') # if so, print that it is in both
        duplicate_count = duplicate_count + 1 # count up the number of duplicate phrases

        # define information for a new row in new merged dataframe
        
        # locate both frequency numbers
        Rhouse_frequency = df_Rhouse.iloc[i]['Frequency'].item() # in the House df row we're in, find Frequency
        Rsenate_frequency = df_Rsenate.loc[df_Rsenate['Noun Phrase'] == phrase, 'Frequency'].item() # in the Senate df row with the same noun phrase, find its frequency in that df

        # and ad the frequencies together
        Rtotal_frequency = Rhouse_frequency + Rsenate_frequency
    
    # if noun phrase on HOUSE list but NOT SENATE list.
    # add the information into a new row
    elif phrase not in df_Rsenate['Noun Phrase'].values:
        print(f'{phrase} is only on House list.')
        house_only_count = house_only_count + 1
    
        # define information for a new row in new merged dataframe
        Rhouse_frequency = df_Rhouse.iloc[i]['Frequency'].item() # in the House df row, find Frequency in the D House list
        Rsenate_frequency = 0
        Rtotal_frequency = Rhouse_frequency

    # now create the row from the above info
    new_row = {
        'noun_phrase': phrase,
        'Rtotal_frequency': Rtotal_frequency,
        'Rhouse_frequency': Rhouse_frequency,
        'Rsenate_frequency': Rsenate_frequency
    }
    
    R_rows.append(new_row)

the secretary is on both the House and Senate lists.
the interior is on both the House and Senate lists.
the state is on both the House and Senate lists.
the bureau is on both the House and Senate lists.
california is on both the House and Senate lists.
natural resources is only on House list.
the united states is on both the House and Senate lists.
access is only on House list.
utah is on both the House and Senate lists.
agriculture is on both the House and Senate lists.
opportunities is on both the House and Senate lists.
ut is only on House list.
the department is on both the House and Senate lists.
oversight is only on House list.
rep. hageman is only on House list.
land is on both the House and Senate lists.
land management is on both the House and Senate lists.
trust is only on House list.
reclamation is only on House list.
rep. don young is only on House list.
the endangered species act is only on House list.
rep. begich is only on House list.
federal lands is only on House list.
certain land is on both the House and Senate lists.
that is on both the House and Senate lists.
rep. curtis is only on House list.
rep. westerman is only on House list.
rep. rob bishop is only on House list.
the national park system is on both the House and Senate lists.
columbia is on both the House and Senate lists.
challenges is only on House list.
sd is only on House list.
rep. boebert is only on House list.
louisiana is on both the House and Senate lists.
arizona is on both the House and Senate lists.
the benefit is only on House list.
federal land is on both the House and Senate lists.
ak is only on House list.
states is on both the House and Senate lists.
rep. hurd is only on House list.
respect is only on House list.
rep. fulcher is only on House list.
rep. mcclintock is only on House list.
congress is only on House list.
virginia is on both the House and Senate lists.
transparency is only on House list.
the mineral leasing act is on both the House and Senate lists.
united states code is on both the House and Senate lists.
rep. johnson is only on House list.
nevada is on both the House and Senate lists.
the use is on both the House and Senate lists.
the district is on both the House and Senate lists.
america is only on House list.
rep. stauber is only on House list.
rep. kennedy is only on House list.
a special resource study is only on House list.
the national park service is only on House list.
certain federal land is on both the House and Senate lists.
the authority is only on House list.
bureau is only on House list.
endangered is only on House list.
a unit is only on House list.
rep. graves is only on House list.
leases is only on House list.
texas is on both the House and Senate lists.
indian country is only on House list.
atmospheric administration is only on House list.
safety is only on House list.
the boundaries is only on House list.
the office is on both the House and Senate lists.
a legislative hearing is only on House list.
accountability is only on House list.
indians is only on House list.
way is only on House list.
wildlife is on both the House and Senate lists.
the discussion draft is only on House list.
wildlife service is only on House list.
rep. lamalfa is only on House list.
rep. valadao is only on House list.
rep. moore is only on House list.
rep. wittman is only on House list.
•	s. is only on House list.
management is on both the House and Senate lists.
implementation is only on House list.
certain lands is only on House list.
barriers is only on House list.
the impacts is on both the House and Senate lists.
energy is on both the House and Senate lists.
rep. scott tipton is only on House list.
missions is only on House list.
alaska is only on House list.
kentucky is on both the House and Senate lists.
health is only on House list.
the president is only on House list.
public lands is on both the House and Senate lists.
(rep. gosar is only on House list.
congressional disapproval is only on House list.
chapter is only on House list.
the rule is only on House list.
rep. ciscomani is only on House list.
ca is only on House list.
rep. leger fernandez is only on House list.
oklahoma is on both the House and Senate lists.
montana is on both the House and Senate lists.
the marine mammal protection act is only on House list.
economic development is only on House list.
an act is only on House list.
washington is on both the House and Senate lists.
certain property is only on House list.
the following bill is only on House list.
mississippi is only on House list.
new york is on both the House and Senate lists.
rep. tom mcclintock is only on House list.
indian lands is only on House list.
new mexico is on both the House and Senate lists.
indian affairs is only on House list.
threatened species is only on House list.
the treaty is only on House list.
the importance is only on House list.
veterans is only on House list.
the pittman-robertson wildlife restoration act is only on House list.
;
•	h.r. is only on House list.
human services is only on House list.
the confederated tribes is only on House list.
subcommittee vote is only on House list.
the future is only on House list.
commerce is only on House list.
ga is only on House list.
rep. stefanik is only on House list.
rep. peltola is only on House list.
federal lands act is only on House list.
rep. kim is only on House list.
rep. tiffany is only on House list.
threatened is only on House list.
plants is only on House list.
rep. ezell is only on House list.
rep. downing is only on House list.
purposes is only on House list.
impacts is only on House list.
the ability is only on House list.
indian tribes is only on House list.
(rep. paul cook is only on House list.
oregon is on both the House and Senate lists.
rep. chris stewart is only on House list.
march is only on House list.
the impact is only on House list.
the conservation is only on House list.
lands is only on House list.
medicare is only on House list.
water is only on House list.

In [12]:
# Also need to add in the noun phrases on the SENATE but not HOUSE lists:
for i in range(1, 150): # run through the rows in the Senate dataframe

    # locate the Noun Phrase in the row were in 
    phrase = df_Rsenate.iloc[i]['Noun Phrase']
    
    # if noun phrase on SENATE list but NOT HOUSE list:
    if phrase not in df_Rhouse['Noun Phrase'].values:
        print(f'{phrase} is only on Senate list.') # print it out
        senate_only_count = senate_only_count + 1 # count up how many phrases are senate only

        # define information for a new row in new merged dataframe
        Rhouse_frequency = 0 
        Rsenate_frequency = df_Rsenate.iloc[i]['Frequency'].item()
        Rtotal_frequency = Rsenate_frequency

        # create a new column in the merged dataframe with the phrase
        new_row = {
        'noun_phrase': phrase,
        'Rtotal_frequency': Rtotal_frequency,
        'Rhouse_frequency': Rhouse_frequency,
        'Rsenate_frequency': Rsenate_frequency
    }   
        R_rows.append(new_row)

a member is only on Senate list.
the environmental protection agency is only on Senate list.
maryland is only on Senate list.
both is only on Senate list.
the federal energy regulatory commission is only on Senate list.
colorado is only on Senate list.
director is only on Senate list.
an assistant secretary is only on Senate list.
a study is only on Senate list.
the nuclear regulatory commission is only on Senate list.
department is only on Senate list.
wyoming is only on Senate list.
secretary is only on Senate list.
florida is only on Senate list.
an assistant administrator is only on Senate list.
deputy secretary is only on Senate list.
tennessee is only on Senate list.
ohio is only on Senate list.
the forest service is only on Senate list.
development is only on Senate list.
the transfer is only on Senate list.
entry is only on Senate list.
north dakota is only on Senate list.
the boundary is only on Senate list.
operation is only on Senate list.
the federal power act is only on Senate list.
the feasibility is only on Senate list.
assistant secretary is only on Senate list.
fish is only on Senate list.
the board is only on Senate list.
directors is only on Senate list.
the tennessee valley authority is only on Senate list.
energy efficiency is only on Senate list.
administrative jurisdiction is only on Senate list.
wilderness is only on Senate list.
bills is only on Senate list.
the wild and scenic rivers act is only on Senate list.
inspector general is only on Senate list.
katharine macgregor is only on Senate list.
pennsylvania is only on Senate list.
the energy policy act is only on Senate list.
demonstration is only on Senate list.
public land is only on Senate list.
a project is only on Senate list.
municipal, rural, and industrial water is only on Senate list.
the federal land policy and management act is only on Senate list.
units is only on Senate list.
robert wallace is only on Senate list.
south carolina is only on Senate list.
nuclear energy is only on Senate list.
all is only on Senate list.
lanny erdos is only on Senate list.
surface mining reclamation is only on Senate list.
enforcement is only on Senate list.
transportation is only on Senate list.
the states is only on Senate list.
the omnibus public land management act is only on Senate list.
the energy independence and security act is only on Senate list.
the administrator is only on Senate list.
the national forest system land is only on Senate list.
the humboldt-toiyabe national forest is only on Senate list.
elko is only on Senate list.
white pine counties is only on Senate list.
a report is only on Senate list.
the maintenance is only on Senate list.
the santa monica mountains national recreation area is only on Senate list.
the rim is only on Senate list.
the valley corridor is only on Senate list.
national recreation areas is only on Senate list.
curry county is only on Senate list.
josephine county is only on Senate list.
all forms is only on Senate list.
appropriation is only on Senate list.
disposal is only on Senate list.
the public land laws is only on Senate list.
location is only on Senate list.
patent is only on Senate list.
the mining laws is only on Senate list.
the mineral leasing and geothermal leasing laws is only on Senate list.
projects is only on Senate list.
renewable energy is only on Senate list.
funds is only on Senate list.
the united states fish and wildlife service is only on Senate list.
environmental protection agency is only on Senate list.
conservation is only on Senate list.
the city is only on Senate list.
the national forest system is only on Senate list.
the john d. dingell is only on Senate list.
jr. conservation is only on Senate list.
recreation act is only on Senate list.
who is only on Senate list.
the national mall is only on Senate list.
a component is only on Senate list.
the colorado wilderness act is only on Senate list.
the sarvis creek wilderness is only on Senate list.
the national wild and scenic rivers system is only on Senate list.
olympic national forest is only on Senate list.
south dakota is only on Senate list.
david lacerte is only on Senate list.
kyle haustveit is only on Senate list.
joshua tree national park is only on Senate list.
jeffrey hall is only on Senate list.
a commemorative work is only on Senate list.
honor is only on Senate list.
the definition is only on Senate list.
assistant administrator is only on Senate list.
alabama is only on Senate list.
administrator is only on Senate list.
solicitor is only on Senate list.

Dill dataframe

In [13]:
df_R = pd.DataFrame(R_rows)

In [14]:
df_R.sort_values(by = 'Rtotal_frequency', ascending=False).head(20)

,noun_phrase,Rtotal_frequency,Rhouse_frequency,Rsenate_frequency
0,the secretary,160,102,58
1,the interior,147,85,62
2,the state,121,70,51
12,the department,54,21,33
6,the united states,44,25,19
3,the bureau,43,33,10
87,energy,42,7,35
4,california,41,31,10
9,agriculture,40,23,17
44,virginia,34,11,23
8,utah,34,23,11
23,certain land,33,16,17
16,land management,32,20,12
5,natural resources,29,29,0
10,opportunities,28,22,6
150,a member,26,0,26
7,access,25,25,0
57,certain federal land,25,9,16
15,land,25,20,5
24,that,24,16,8

### Sort by total frequency and reset indices ###

In [15]:
df_D.sort_values(by = 'Dtotal_frequency', ascending=False)
df_D.reset_index(drop=True, inplace=True)

df_R.sort_values(by = 'Rtotal_frequency', ascending=False).reset_index(drop=True, inplace=True)
df_R.reset_index(drop=True, inplace=True)

In [16]:
df_D.head(40)

,noun_phrase,Dtotal_frequency,Dhouse_frequency,Dsenate_frequency
0,the interior,68,13,55
1,the secretary,77,13,64
2,the department,38,11,27
3,representatives,11,11,27
4,america,9,9,27
5,the bureau,15,8,7
6,the state,77,7,70
7,priorities,6,6,70
8,""" legislative hearing",6,6,70
9,public lands,10,6,4
10,impacts,6,6,4
11,california,17,5,12
12,public health,5,5,12
13,oversight,5,5,12
14,the environment,5,5,12
15,the impacts,5,5,12
16,reclamation,9,5,4
17,climate change,5,5,4
18,communities,10,5,5
19,solutions,4,4,5
20,access,4,4,5
21,the policies,4,4,5
22,land management,12,4,8
23,rep. pete stauber,4,4,8
24,the mineral withdrawal,4,4,8
25,the superior national forest,4,4,8
26,indigenous communities,4,4,8
27,coastal communities,3,3,8
28,environmental justice,3,3,8
29,enforcement,3,3,8
30,all act,3,3,8
31,(virtual hearing,3,3,8
32,diversity,3,3,8
33,lessons,3,3,8
34,the need,3,3,8
35,the interior’s spending priorities,3,3,8
36,health care,3,3,8
37,consumers,3,3,8
38,the u.s. territories,3,3,8
39,the future,3,3,8

In [17]:
df_R.head(40)

,noun_phrase,Rtotal_frequency,Rhouse_frequency,Rsenate_frequency
0,the secretary,160,102,58
1,the interior,147,85,62
2,the state,121,70,51
3,the bureau,43,33,10
4,california,41,31,10
5,natural resources,29,29,0
6,the united states,44,25,19
7,access,25,25,0
8,utah,34,23,11
9,agriculture,40,23,17
10,opportunities,28,22,6
11,ut,22,22,0
12,the department,54,21,33
13,oversight,21,21,0
14,rep. hageman,21,21,0
15,land,25,20,5
16,land management,32,20,12
17,trust,20,20,0
18,reclamation,20,20,0
19,rep. don young,18,18,0
20,the endangered species act,18,18,0
21,rep. begich,18,18,0
22,federal lands,17,17,0
23,certain land,33,16,17
24,that,24,16,8
25,rep. curtis,15,15,0
26,rep. westerman,15,15,0
27,rep. rob bishop,14,14,0
28,the national park system,21,14,7
29,columbia,20,14,6
30,challenges,14,14,0
31,sd,14,14,0
32,rep. boebert,14,14,0
33,louisiana,17,13,4
34,arizona,18,13,5
35,the benefit,13,13,0
36,federal land,17,13,4
37,ak,13,13,0
38,states,19,13,6
39,rep. hurd,13,13,0

### Define different lists of Noun Phrases of interst by manually looking through and categorizing ###


Manually make some lists of phrases

In [ ]:
not_interesting = [
    
    # actors
    'the united states', 'america', 'congress', 'a member', 'chairman', 'assistant secretary', 'the secretary',
    'deputy secretary', 'department', 'director', 'an assistant secretary', 'office', 'the administrator', 'a member'

    # agencies/departments

    'the office' , 'the state', 'an assistant administrator', 'the department', 'secretary'
    'assistant administrator', 'federal cochairperson', 'subcommittee vote', '" legislative hearing', ';•	h.r.'

    #filler words
    'that', 'all', 'both', 'which', '.', '-', 'each', '•	s.', 'day', 'way', 'that', 'who',
    
    # neutral policy words and others to filter out
    'the policies', 'a unit', 'components', 'priorities', 'entry', 'the use', 'a study', 'a program', 'program', 'a pilot program',
    '(virtual hearing', 'h.res', 'a legislative hearing', 'the discussion draft', 'those acts', 'the designation',

    # because i'm including 'district of columbia'
    'columbia', 'the district',

    #healthcare words
    'health care', 'pandemics', "covid-19’s impact", 'mental health', 'biomedical research', 'biomedicine', 'patent', 'agriculture',

    # other subjects
    '“miners pension protection act',  'agriculture', 'medicare', 'mmiw', #missing and murdered indigenous women,

]

legislation_and_initiatives = [
    'the omnibus public land management act',
    'the alaska native claims settlement act',
    'the wild and scenic rivers act',
    'the mining law',
    'the bipartisan infrastructure law',
    'the mineral leasing act',
    'united states code',
    'the marine mammal protection act',
    'the energy policy act',
    'the endangered species act',
    'miners act',
    'res.14',
    'h.res.1253',
    "america's wildlife act",
    'the president’s fiscal year 2020 budget proposal',
    'the surface mining control and reclamation act',
    'puerto rico self-determination act',
    'the forest and rangeland renewable resources planning act',
    'the infrastructure investment and jobs act',
    'historic preservation',
    'the energy independence and security act',
    'elko',
    'the pittman-robertson wildlife restoration act',
    'the federal power act',
    'h.res.1252',
    'h.res.1247',
    'the smith river national recreation area act',
    'jr. conservation',
    'recreation act',
    'the colorado wilderness act'
    'the mineral leasing and geothermal leasing laws',
    'the smith river national recreation area act',
    'the clean air act', 'clean air act',
    'federal lands act', 'the federal land and policy management act'

]

places = [
    'alabama', 'al',
    'alaska', 'ak',
    'arizona', 'az',
    'arkansas', 'ar',
    'california', 'ca',
    'colorado', 'co',
    'connecticut', 'ct',
    'delaware', 'da',
    'district of columbia', 'dc', 'd.c.',
    'florida', 'fl',
    'georgia', 'ga',
    'hawaii', 'hi',
    'idaho', 'id',
    'illinois', 'il',
    'indiana', 'in',
    'iowa', 'ia',
    'kansas', 'ks',
    'kentucky', 'ky',
    'louisiana', 'la',
    'maine', 'me',
    'maryland', 'md',
    'massachusetts', 'ma',
    'michigan', 'mi',
    'minnesota', 'mn',
    'mississippi', 'ms',
    'missouri', 'mo',
    'montana', 'mt',
    'nebraska', 'ne',
    'nevada', 'nv',
    'new hampshire', 'nh',
    'new jersey', 'nj',
    'new mexico', 'nm',
    'new york', 'ny',
    'north carolina', 'nc',
    'north dakota', 'nd',
    'ohio', 'oh',
    'oklahoma', 'ok',
    'oregon', 'or',
    'pennsylvania', 'pa',
    'rhode island', 'ri',
    'south carolina', 'sc',
    'south dakota', 'sd',
    'tennessee', 'tn',
    'texas', 'tx',
    'utah', 'ut',
    'vermont', 'vt',
    'virginia', 'va',
    'washington', 'wa',
    'west virginia', 'wv',
    'wisconsin', 'wi',
    'wyoming', 'wy',

    # other geographic words 

    'southern', 'south',
    'northern', 'north', 'northeast','northeastern', 
    'midwest',
    'pacific northwest',
    'west', 'western', 
    'coastal',
    'gulf coast', 'permian basin', 'gulf of mexico', 'gulf of america'
    'rust belt',
    'sun belt',
    'bible belt',
    'new england',
    'great lakes',
    'appalachia',
    'rural',
    'urban', 'cities', 'city',
    'suburban', 'suburb',
    
    # from spacy's own analysis:
    'the santa monica mountains national recreation area',
    'the rim',
    'the valley corridor',
    'olympic national forest',
    'the dolores river special management area', 'the dolores river national conservation area',
    'the continental divide national scenic trail',
    'the smith river national recreation area',
    'the rio grande del norte national monument',
    'josephine county',
    'curry county',
    'white pine counties',
    'the national mall',
    'elko',
    'the national forest system land',
    'the humboldt-toiyabe national forest',
    'the sarvis creek wilderness',
    'joshua tree national park',
    'the national wild and scenic rivers system',
]

federal_actors = [
    'david m. uhlmann',
    'the united states fish and wildlife service',
    'the nuclear regulatory commission',
    'the forest service',
    'laura daniel-davis',
    'sara c. bronin',
    'the president',
    'inspector general',
    'the advisory council',
    'the environmental protection agency', 'environmental protection agency',
    'the federal energy regulatory commission',
    'fish and wildlife service', 'fish & wildlife service'
    'the national park service', 'the national park system',
    'bureau of land management', 'blm',
    'the national oceanic',
    'u.s. fish', 'wildlife service'
    'joseph goffman',
    'the john d. dingell',
    'carlton waterhouse',
    'solicitor',
    'david lacerte',
    'katharine macgregor',
    'the bureau', 'bureau',
    'the interior',
    'the united states courthouse',
    'the interior’s departmental ethics office',
    'david crane',
    'the federal highway administration',
    'the national park service',
    'kyle haustveit',
    'jeffrey hall',
    'joseph goffman,'
]

lawmakers = [
    '(rep. lamborn',
    'rep. begich',
    'rep. westerman',
    'rep. mcclintock',
    'rep. kennedy',
    'rep. hageman',
    'rep. hurd',
    'rep. don young'
    'rep. boebert',
    'rep. pete stauber',
    'rep. boebert',
    'rep. don young',
    'rep. curtis',
    'rep. johnson'
    'rep. johnson',
    'rep. fulcher',
    'rep. rob bishop',
    'rep. stauber',
    '(rep. gosar',
    'rep. valadao',
    'rep. lamalfa',
    'rep. ezell',
    'rep. downing',
    'rep. moore',
    'rep. wittman',
    'rep. ciscomani',
    'rep. leger fernandez',
    'rep. dingell',
    'rep. randall',
    '(rep. maloy',
    'rep. graves',
    'representatives',
    'rep. johnson',
    'rep. huffman',
    '(rep. paul cook',
    'rep. chris stewart',
    'rep. tom mcclintock',
    'rep. tiffany',
    '(ranking member bruce westerman',
    '(rep. lamborn',
    'rep. stefanik',
    'rep. peltola',
    'rep. kim',
    'rep. scott tipton'
]

### Now make a new column in each of the the dataframes with the category, to enable sorting ###

First, sort phrases into buckets

In [19]:
# Define a function to categorize each individual item

def assign_phrase_category(item):
    if item in not_interesting:
        return "not interesting"
    elif item in places:
        return "place"
    elif item in lawmakers:
        return "lawmaker"
    elif item in federal_actors:
        return "actor"
    elif item in legislation_and_initiatives:
        return "legislation"
    else:
        return "general"

In [20]:
# Define phrase category

df_D['phrase_category'] = df_D['noun_phrase'].apply(assign_phrase_category)
df_R['phrase_category'] = df_R['noun_phrase'].apply(assign_phrase_category)

In [21]:
# print out how many of each category to make sure it worked

print(df_D['phrase_category'].value_counts())
print(df_R['phrase_category'].value_counts())

phrase_category
general            150
not interesting     47
place               36
legislation         22
actor               21
lawmaker             5
Name: count, dtype: int64
phrase_category
general            120
place               46
not interesting     32
lawmaker            31
actor               18
legislation         12
Name: count, dtype: int64

Create .csvs with each of the categories

In [22]:
#Democrats

general = df_D[df_D['phrase_category'] == 'general'].sort_values(by='Dtotal_frequency', ascending=False)
places = df_D[df_D['phrase_category'] == 'place'].sort_values(by='Dtotal_frequency', ascending=False)
lawmakers = df_D[df_D['phrase_category'] == 'lawmaker'].sort_values(by='Dtotal_frequency', ascending=False)
federal_actors = df_D[df_D['phrase_category'] == 'federal_actor'].sort_values(by='Dtotal_frequency', ascending=False)
leg_and_initiatives = df_D[df_D['phrase_category'] == 'legislation_and_initiatives'].sort_values(by='Dtotal_frequency', ascending=False)


general.to_csv('D_top_generalphrases.csv')
places.to_csv('D_top_placephrases.csv')
lawmakers.to_csv('D_top_lawmakerphrases.csv')
federal_actors.to_csv('D_top_actorphrases.csv')
leg_and_initiatives.to_csv('D_top_legandinitiatives.csv')

In [23]:
# Republicans

general = df_R[df_R['phrase_category'] == 'general'].sort_values(by='Rtotal_frequency', ascending=False)
places = df_R[df_R['phrase_category'] == 'place'].sort_values(by='Rtotal_frequency', ascending=False)
lawmakers = df_R[df_R['phrase_category'] == 'lawmaker'].sort_values(by='Rtotal_frequency', ascending=False)
actors = df_R[df_R['phrase_category'] == 'actor'].sort_values(by='Rtotal_frequency', ascending=False)

federal_actors = df_R[df_R['phrase_category'] == 'federal_actor'].sort_values(by='Rtotal_frequency', ascending=False)
leg_and_initiatives = df_R[df_R['phrase_category'] == 'legislation_and_initiatives'].sort_values(by='Rtotal_frequency', ascending=False)

general.to_csv('R_top_generalphrases.csv')
places.to_csv('R_top_placephrases.csv')
lawmakers.to_csv('R_top_lawmakerphrases.csv')
federal_actors.to_csv('R_top_actorphrases.csv')
leg_and_initiatives.to_csv('R_top_legandinitiatives.csv')